---
title: "Analysis on the Lydia's dataset"
---

* Estimer la variance $\sigma$
* Choisir un niveau de coupe $(1+\kappa)\sigma$
* Nouveux échantillon $X + \varepsilon_i$
* Test bimodal sur un seul des deux cotés

```{r}
microMA_WT_growthRates <- read.csv2("data_microMA/dataset_microMA_WT_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MutH_growthRates <- read.csv2("data_microMA/dataset_microMA_MutH_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MutT_growthRates <- read.csv2("data_microMA/dataset_microMA_MutT_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MF1_growthRates <- read.csv2("data_microMA/dataset_microMA_MF1_growthRates_RMdead_NAab.csv", row.names = 1)

# Plot 
plot(microMA_WT_growthRates[, 4], type="l")
plot(microMA_MF1_growthRates[, 4], type="l")
#plot(microMA_WT_growthRates$time, microMA_WT_growthRates[, 6], type="l", xlab = "Time (hrs)", ylab = "Growth rate")
```

## Compute the jump : W_t - W_{t-1}

```{r}

library('goft')
library('resample')
options(repr.plot.width = 15, repr.plot.height = 10)

quotient_diff <- function(x) {
  return(x[-1] / x[-length(x)])
}
growth_WT<- sapply(microMA_WT_growthRates, quotient_diff)
growth_WT <- growth_WT[growth_WT != 1 & is.finite(growth_WT)]

#growth_WT<- -sapply(microMA_WT_growthRates, diff)
#growth_WT <- growth_WT[growth_WT != 0 & is.finite(growth_WT)]

par(mfrow=c(2,1))
limit = 0.012
growth_WT_dty <- hist(growth_WT, breaks=500, probability = TRUE, main="Distribution of gross growth rate changes")
growth_WT_norm_dty <- dnorm(growth_WT_dty$mids, mean(growth_WT[abs(growth_WT)<limit]), sd(growth_WT[abs(growth_WT)<limit]))

growth_WT_dty2 <- hist(growth_WT, breaks=1000, probability = TRUE, xlim=c(0,2), main="Distribution of gross growth rate changes")
growth_WT_norm_dty2 <- dnorm(growth_WT_dty2$mids, mean(growth_WT[abs(growth_WT)<limit]), sd(growth_WT[abs(growth_WT)<limit]))

# Gaussian test ?  :
growth_WT_sd = sd(growth_WT,na.rm=TRUE)
growth_WT_mean = mean(growth_WT,na.rm=TRUE)
growth_WT_norm = (growth_WT-growth_WT_mean)/growth_WT_sd

print(growth_WT_sd)
ks.test(growth_WT_norm[1:100], "pnorm")
shapiro.test(growth_WT_norm[1:100])
```


```{r}
options(repr.plot.width = 15, repr.plot.height = 30)
qqnorm(growth_WT_norm[1:5000])
qqline(growth_WT_norm[1:5000])
```

## Print the real data (MUTH)

```{r}
options(repr.plot.width = 15, repr.plot.height = 10)

growth_MutH <- sapply(microMA_MutH_growthRates, quotient_diff)
growth_MutH <- growth_MutH[growth_MutH != 1 & is.finite(growth_MutH)]

par(mfrow=c(2,1))
limit = 0.012

growth_MutH_hist <- hist(growth_MutH, breaks=500, probability = TRUE, main="Distribution of gross growth rate changes")
growth_MutH_hist2 <- hist(growth_MutH, breaks=1000, probability = TRUE, xlim=c(0,2), main="Distribution of gross growth rate changes")

# Gaussian test ?  :
growth_MutH_sd = sd(growth_MutH,na.rm=TRUE)
growth_MutH_mean = mean(growth_MutH,na.rm=TRUE)
growth_MutH_norm = (growth_MutH-growth_MutH_mean)/growth_MutH_sd

print(growth_MutH_sd)
ks.test(growth_MutH_norm[1:100], "pnorm")
shapiro.test(growth_MutH_norm[1:100])
```

## Print the real data (MF1)

```{r}
options(repr.plot.width = 15, repr.plot.height = 10)

growth_MF1 <- sapply(microMA_MF1_growthRates, quotient_diff)
growth_MF1 <- growth_MF1[growth_MF1 != 1 & is.finite(growth_MF1)]

par(mfrow=c(2,1))
limit = 0.012

growth_MF1_hist <- hist(growth_MF1, breaks=500, probability = TRUE, main="Distribution of gross growth rate changes")
growth_MF1_hist2 <- hist(growth_MF1, breaks=1000, probability = TRUE, xlim=c(0,2), main="Distribution of gross growth rate changes")

# Gaussian test ?  :
growth_MF1_sd = sd(growth_MF1,na.rm=TRUE)
growth_MF1_mean = mean(growth_MF1,na.rm=TRUE)
growth_MF1_norm = (growth_MF1-growth_MF1_mean)/growth_MF1_sd

print(growth_MF1_sd)
shapiro.test(growth_MF1_norm[1:5000])
lnorm_test(growth_MF1[1:5000])
ks.test(growth_MF1_norm[1:5000], "pnorm")
```

### Cutting

```{r}
options(repr.plot.width = 15, repr.plot.height = 10)

growth_MF1 <- sapply(microMA_MF1_growthRates, quotient_diff)
growth_MF1 <- growth_MF1[growth_MF1 != 1 & is.finite(growth_MF1)]
growth_MF1_plus <- growth_MF1[abs(growth_MF1) >= (1+growth_WT_sd)*1.5]
print(growth_WT_sd)

par(mfrow=c(2,1))

growth_MF1_hist2 <- hist(growth_MF1_plus, breaks=1000, probability = TRUE, main="Distribution of gross growth rate changes with cutting")
growth_MF1_hist2 <- hist(growth_MF1_plus, breaks=100, probability = TRUE, xlim=c(1.7,2.5), main="Distribution of gross growth rate changes with cutting")

# Gaussian test ?  :
growth_MF1_sd = sd(growth_MF1,na.rm=TRUE)
growth_MF1_mean = mean(growth_MF1,na.rm=TRUE)
growth_MF1_norm = (growth_MF1-growth_MF1_mean)/growth_MF1_sd

print(growth_MF1_sd)
shapiro.test(growth_MF1_norm[1:5000])
lnorm_test(growth_MF1[1:5000])
ks.test(growth_MF1_norm[1:5000], "pnorm")
```


```{r}
library(multimode)
library(mclust)
modetest(growth_MF1_plus,mod0=1,method="FM",B=5,n=NULL,tol=NULL)
```



# Analyse du bruit direct : 
```{r}
direct_noise <- read.csv2("data_microMA/dataset_microMA_WT_growthRates_RMdead_NAab.csv", row.names = 1)
direct_noise_mean = colMeans(direct_noise, na.rm=TRUE)
#direct_noise_var = colVars(direct_noise, na.rm=TRUE)
noise_norm <- (direct_noise-direct_noise_mean)

noise_norm <- noise_norm[!is.na(noise_norm)]

#print(colMeans(direct_noise, na.rm=TRUE))
direct_noise_d <- noise_norm

hist(direct_noise_d, breaks=50, probability = TRUE)
ks.test(direct_noise_d[1:100], "pnorm")
shapiro.test(direct_noise_d[1:100])

qqnorm(direct_noise_d[1:5000])
qqline(direct_noise_d[1:5000])

```


