---
title: "Use the R-multimode package on the data of Lydia"
---




```{r}
microMA_WT_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_WT_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MutH_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_MutH_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MutT_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_MutT_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MF1_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_MF1_growthRates_RMdead_NAab.csv", row.names = 1)
```

### Rate of growth

```{r}
options(repr.plot.width = 15, repr.plot.height = 10)

drops_MutH <- -sapply(microMA_MutH_growthRates_RMdead_NAab, diff)
drops_MutH <- drops_MutH[drops_MutH != 0 & is.finite(drops_MutH)]

par(mfrow=c(2,1))
limit = 0.012
drops_MutH_dty <- hist(drops_MutH, breaks=500, probability = TRUE, main="Distribution of gross growth rate changes")
drops_MutH_norm_dty <- dnorm(drops_MutH_dty$mids, mean(drops_MutH[abs(drops_MutH)<limit]), sd(drops_MutH[abs(drops_MutH)<limit]))
lines(drops_MutH_dty$mids, drops_MutH_norm_dty*0.95, col = "red", lwd=2)

drops_MutH_dty2 <- hist(drops_MutH, breaks=1000, probability = TRUE, xlim=c(-0.02,0.02), main="Distribution of gross growth rate changes")
drops_MutH_norm_dty2 <- dnorm(drops_MutH_dty2$mids, mean(drops_MutH[abs(drops_MutH)<limit]), sd(drops_MutH[abs(drops_MutH)<limit]))
lines(drops_MutH_dty2$mids, drops_MutH_norm_dty2*0.95, col = "red", lwd=2)
```

### Relative Growth
```{r}
W <- microMA_WT_growthRates_RMdead_NAab[1:200,]

reldrops_WT <- -sapply(W, diff)/W[-dim(W)[1],]
reldrops_WT <- reldrops_WT[reldrops_WT != 0]    # remove constant growth rates
reldrops_WT <- reldrops_WT[is.finite(reldrops_WT)]    # remove reborn dead cells (division by 0)

length(reldrops_WT)
summary(reldrops_WT)
hist(reldrops_WT, breaks=100)
```