---
title: "Use the R-multimode package on the data of Lydia"
---




```{r}
library("gridExtra")
library("ggplot2")
library("zoo")
library("MASS")
```

# data

```{r}
microMA_WT <- read.csv2("Donnees_article/All_data/data_microMA/dataset_microMA_WT.csv")
microMA_MutH <- read.csv2("Donnees_article/All_data/data_microMA/dataset_microMA_MutH.csv")
microMA_MF1 <- read.csv2("Donnees_article/All_data/data_microMA/dataset_microMA_MF1.csv")
microMA_MutT <- read.csv2("Donnees_article/All_data/data_microMA/dataset_microMA_MutT.csv")

# Split the channel information (first 2 rows) from the growth rates
microMA_WT_channels <- microMA_WT[c(1,2),]
microMA_WT <- microMA_WT[-c(1,2),]
microMA_MutH_channels <- microMA_MutH[c(1,2),]
microMA_MutH <- microMA_MutH[-c(1,2),]
microMA_MF1_channels <- microMA_MF1[c(1,2),]
microMA_MF1 <- microMA_MF1[-c(1,2),]
microMA_MutT_channels <- microMA_MutT[c(1,2),]
microMA_MutT <- microMA_MutT[-c(1,2),]
microMA_MutH_growthRates <- microMA_MutH[seq(3, dim(microMA_MutH)[2], 3)]
microMA_MutH_growthRates[microMA_MutH_growthRates<0] <- NA  # Set negative growth rates to NA

microMA_WT_growthRates <- microMA_WT[seq(3, dim(microMA_WT)[2], 3)]
microMA_WT_growthRates[microMA_WT_growthRates<0] <- NA  # Set negative growth rates to NA

microMA_MutT_growthRates <- microMA_MutT[seq(3, dim(microMA_MutT)[2], 3)]
microMA_MutT_growthRates[microMA_MutT_growthRates<0] <- NA  # Set negative growth rates to NA

microMA_MF1_growthRates <- microMA_MF1[seq(3, dim(microMA_MF1)[2], 3)]
microMA_MF1_growthRates[microMA_MF1_growthRates<0] <- NA  # Set negative growth rates to NA


par(mfrow=c(3,2), mar = c(4, 4, 2, 2))
options(repr.plot.width = 12, repr.plot.height = 6, repr.plot.res = 150)

for (i in 1:6){
    plot(microMA_MutH$time/60, microMA_MutH_growthRates[, i], type="l", xlab = "Time (hrs)", ylab = "Growth rate", main = paste("Example",i,"of growth rate evolution"))
}
tmin=1
tmax=44*15
threshold <- 0.003
keep_cells <- FALSE  # wether to keep early cells even if the mother cell dies later on

print("WT")
first_slow_cell <- function(x, threshold){
    return (min(which(x<threshold), na.rm=T))
}

remove_NA_cols <- function(GR){
    return(GR[!sapply(GR, function(x)all(is.na(x)))])
}

remove_slow_GR <- function(GR, threshold, keep_cells, tmin, tmax, verbose=FALSE){
     # Identify channels with >80h of slow growth (dead mother cell)
     slow_channels <- which(colSums(GR[1:(tmax+20),]<threshold, na.rm=T)>20)
     
     if (keep_cells){
         d <- dim(GR[slow_channels])
         # Find the first slow growth rate time and set all following growth rates to NA
         first_slow_time <- sapply(GR[slow_channels], first_slow_cell, threshold)
         GR_to_remove <- sapply(first_slow_time, function(t){matrix(1:d[1], d) >= max(t-10, 0)})
         GR[slow_channels][GR_to_remove] <- NA
    }else if(length(slow_channels)!=0){
         GR <- GR[-slow_channels]
    }
    if (verbose){print(paste("slow_channels :", length(slow_channels))); print(dim(GR))}
    return (remove_NA_cols(GR[tmin:tmax,]))
 }

print("WT")
microMA_WT_growthRates_RMdead <- remove_slow_GR(microMA_WT_growthRates, threshold, keep_cells, tmin, tmax, verbose=T)

print("MutH")
microMA_MutH_growthRates_RMdead <- remove_slow_GR(microMA_MutH_growthRates, threshold, keep_cells, tmin, tmax, verbose=T)

print("MutT")
microMA_MutT_growthRates_RMdead <- remove_slow_GR(microMA_MutT_growthRates, threshold, keep_cells, tmin, tmax, verbose=T)

print("MF1")
microMA_MF1_growthRates_RMdead <- remove_slow_GR(microMA_MF1_growthRates, threshold, keep_cells, tmin, tmax, verbose=T)

```


```{r}
par(mfrow=c(4,2), mar = c(4, 4, 2, 2))
options(repr.plot.width = 12, repr.plot.height = 8, repr.plot.res = 150)

for (i in c(8,9, 10,12)){
    plot(tmin:tmax*4/60, microMA_MutH_growthRates[tmin:tmax, i], type="l", xlab = "Time", ylab = "Growth rate", main = paste("Example",i,"of growth rate evolution"))
    plot(tmin:tmax*4/60, microMA_MutH_growthRates_RMdead[,i], type="l", xlab = "Time", ylab = "Growth rate", main = paste("Example",i,"of growth rate evolution without dead cells"))
}
```



```{r}
microMA_WT_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_WT_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MutH_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_MutH_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MutT_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_MutT_growthRates_RMdead_NAab.csv", row.names = 1)
microMA_MF1_growthRates_RMdead_NAab <- read.csv2("Donnees_article_modifiees/data_microMA/dataset_microMA_MF1_growthRates_RMdead_NAab.csv", row.names = 1)
```

### Rate of growth

```{r}
options(repr.plot.width = 15, repr.plot.height = 10)

drops_MutH <- -sapply(microMA_MutH_growthRates_RMdead_NAab, diff)
drops_MutH <- drops_MutH[drops_MutH != 0 & is.finite(drops_MutH)]

par(mfrow=c(2,1))
limit = 0.012
drops_MutH_dty <- hist(drops_MutH, breaks=500, probability = TRUE, main="Distribution of gross growth rate changes")
drops_MutH_norm_dty <- dnorm(drops_MutH_dty$mids, mean(drops_MutH[abs(drops_MutH)<limit]), sd(drops_MutH[abs(drops_MutH)<limit]))
lines(drops_MutH_dty$mids, drops_MutH_norm_dty*0.95, col = "red", lwd=2)

drops_MutH_dty2 <- hist(drops_MutH, breaks=1000, probability = TRUE, xlim=c(-0.02,0.02), main="Distribution of gross growth rate changes")
drops_MutH_norm_dty2 <- dnorm(drops_MutH_dty2$mids, mean(drops_MutH[abs(drops_MutH)<limit]), sd(drops_MutH[abs(drops_MutH)<limit]))
lines(drops_MutH_dty2$mids, drops_MutH_norm_dty2*0.95, col = "red", lwd=2)
```

### Relative Growth
```{r}
W <- microMA_WT_growthRates_RMdead_NAab[1:200,]

reldrops_WT <- -sapply(W, diff)/W[-dim(W)[1],]
reldrops_WT <- reldrops_WT[reldrops_WT != 0]    # remove constant growth rates
reldrops_WT <- reldrops_WT[is.finite(reldrops_WT)]    # remove reborn dead cells (division by 0)

length(reldrops_WT)
summary(reldrops_WT)
hist(reldrops_WT, breaks=100)
```